### ISSUE TITLE
Issue with booting (boot loop) - Only works with BIOS A09 

### ISSUE THREAD

**Issue by BillDH2k** [NOTNlCE/Dell-Precision-T5810-OpenCore#2]
Hi, I tried your newer EFI but experienced a booting issue (same symptom with your previous OC 064 EFI). The EFI works great under BIOS A09 (fresh install or boot from an existing Big Sur). But as soon as I upgrade the BIOS to a newer version (tried A033, as well A11), I would run into a boot loop: Error "StartImage failed - Aborted", then back to OC picker screen (OC log is attached).

The only key item I changed was CpuId1data, to "C3060300 00000000 00000000 00000000", as I have a V3 Xeon (Haswell-E).

Tried on two T5810's, with exactly the same results. One is 2667V3, Sata SSD, R290X. The 2nd one is 1620V3, Sata SSD, HD 7850 2GB. No other add-on's. 

One thing I am not sure is the BIOS settings: I've tried to keep the BIOS settings the same as before (as of A09). But again, not sure what the "correct" settings should be. I'll post the important settings here later, if that helps to identify the root cause.

[opencore-Log-2.txt](https://github.com/NOTNlCE/Dell-Precision-T5810-OpenCore/files/8475407/opencore-Log-2.txt)

Really appreciated if you could shed some light here.

In the end, I could just stay with A09 BIOS, as it works just fine for me.

Thanks in advance!

**Comment by NOTNlCE** [comment]
Interesting. Here are my BIOS settings in use on A33:

Advanced Boot Options - > Enable Legacy Option ROMs -> True
Integrated NIC -> Enabled, no UEFI Network Stack
Serial Port -> Disabled
SATA Operation -> AHCI
All Drives Enabled
(No other pertinent options in the menu until: TPM)
TPM 1.2 Security -> Disabled
Computrace -> Deactivate
CPU XD Support -> Enabled
Secure Boot Enable -> Disabled [It is possible this is the big chance since A09?]
(Another set of non-pertinent settings here, moving down to Virtualization Support)
Virtualization -> Enabled
VT for Direct I/O -> Disabled [macOS does not support this anyway]

That should be it? Under "Advanced Configurations" both options are set to Auto for me. 

Looking at your debg (very helpful by the way, thank you) I would suspect there is a boot signature issue somewhere, either in NVRAM or in BIOS (TPM on, Secure Boot Enabled?)

**Comment by BillDH2k** [comment]
Thank you for your quick reply. I did a quick check of my BIOS, hasn't found anything inconsistent to yours. I will do a "ClearVRAM" to see if that makes any difference (just need to figure how to add that option in OC picker screen).

**Comment by NOTNlCE** [comment]
If using this EFI, you can disable "Hide Auxiliary" in the "Misc" section of your config.plist to show it at boot menu. Unsure what else could be inconsistent between the two... I have not done any BIOS mods or additional patching vs. what is present in this EFI. 

Also, if you are not doing so already, generate a proper serial, UUID, and MLB for your config.plist. This repository has them stripped in SMBIOS. 

EDIT:

There are a few items referencing this error... https://github.com/acidanthera/bugtracker/issues/979 

Your CPU is different, which seems the only change. Some people suggest enabling "DevirtualiseMmio" quirk in Booter section of config.plist, but this is disabled in my config.plist and in my primary X99-based system running a v3 Xeon. Another suggestion is to try and boot up with only one disk attached to the system.

**Comment by BillDH2k** [comment]
Just want to report back that I tried "ClearVRAM", as well as, "Reset VRAM". Did not fix the issue, same error.

Also tried with "DeviceVirtualiseMmio" set to TRUE, trying to run Big Sur USB install. This time it went further, last OC file log sentence: "[EB|LOG:EXITBS:START]...", so it passed this step (OC log attached). Then in next phase, shortly, kernel panicked, according to msg on screen. I attached picture of screen shot, if it is useful for anyone trying to identify the cause.
[opencore-Log-4-DevVirtualiseMmio.txt](https://github.com/NOTNlCE/Dell-Precision-T5810-OpenCore/files/8477830/opencore-Log-4-DevVirtualiseMmio.txt)

![20220412_222656](https://user-images.githubusercontent.com/89153638/163090498-7ba9057f-fcfa-4f74-a0b8-a926e6c40a35.jpg)

For now, I will revert back to BIOS A09, but I will keep one of my system in A33 for further testing, if necessary.

Thank you for your help!

BTW - I did create a new set of serial #'s, etc.

**Comment by BillDH2k** [comment]
Also another point: the same thing happened on my setup with your previous EFI (OC064), so I tend to think this is more likely related to my machine settings, rather than OpenCore.

**Comment by BillDH2k** [comment]
Just to want to report back some progress here. Played with A33 BIOS settings, then suddenly, one of the unit started booting up the OC! So I wrote down the BIOS settings, verified again that I could go fresh USB install (Big Sur) and boot from an existing install (Big Sur/Catalina). Then copied the same BIOS settings to the other T5810 (also A33), but the it failed to boot! 

There are some difference btw the two units: the working one has TPM 2.0, while the other has TPM 1.2. CPU is a not a factor since I tried to swap the CPUs, and got the same result (1620V3 vs 2666V3). 

Attached is the BIOS settings I recorded from the T5810 unit with TPM 2.0. I did not try to figure out which setting is critical for your OC to boot. This one setting was tested to work.

Could you please copy down your BIOS settings which was known to work? Your has TPM 1.2, I believe. I would like to try these setting on my unit. 
[T5810-A33-TPM2.0-Bios-Settings.txt](https://github.com/NOTNlCE/Dell-Precision-T5810-OpenCore/files/8550590/T5810-A33-TPM2.0-Bios-Settings.txt)

Thanks in advance!

**Comment by NOTNlCE** [comment]
Attached are my BIOS settings on my unit. It does have TPM 1.2, not 2.0. Notable changes are:

Enable Legacy Option ROMs - YES (Required for my card, no UEFI vBIOS)
Memory Map IO Above 4G - YES
OROM Keyboard Access - YES (Shouldn't impact OC launch)
Dell Reliable Memory Technology (RMT) - NO

All others are the same.
[T5810-A33-TPM1.2-Bios-Settings.txt](https://github.com/NOTNlCE/Dell-Precision-T5810-OpenCore/files/8566498/T5810-A33-TPM1.2-Bios-Settings.txt)

**Comment by BillDH2k** [comment]
Thank you for posting your BIOS settings. My 1st trial with these setting failed :(. The BIOS of T5810 is indeed very moody with macOS. I will try to experiment a little more with it and report back later.

**Comment by BillDH2k** [comment]
More feedback. Played more with the setting. Eventually succeeded. Concluded that one settings is critical: [Memory Map IO above 4GB]. Either [YES] or [NO] worked. But I had to toggle it at least once, so during the switching, BIOS some how re-initialized the settings (??) to make it pass. You could tell that since the system power off briefly then back again (not a normal boot sequence).

There is still one issue, however, that only AMD cards worked (7850 HD, R9 390), but nVidia cards (K5000, GTX 670) failed (reboot after panic). I will investigate more and report back.

Thanks.

**Comment by NOTNlCE** [comment]
Fantastic - the memory map would explain the memory error when launching OpenCore with one of the systems. Are you able to post a copy of the kernel panic with the NVIDIA cards? The machine I have used to have a GTX 660 (Kepler) installed, though that card has issues in macOS. I have not tested with a Kepler GPU since getting my AMD card. I can throw one in and check results.

**Comment by BillDH2k** [comment]
OK. I will try to catch the screen with my phone video. The messages were just flying through the screen too fast.

**Comment by NOTNlCE** [comment]
You can log the crash reports to EFI using OpenCore debug properties: https://github.com/dortania/OpenCore-Install-Guide/blob/master/troubleshooting/debug.md

**Comment by BillDH2k** [comment]
Finally solved the issue! You have a DeviceProperties entry for "HD 7850", which caused a conflict with nVidia card. After removing that entry, macOS booted right up!  I initially thought that entry was just cosmetic description. Also, without it, HD 7850 boot up just fine. So, it could be removed.

So, this completes my test run with your EFI and the conclusion is that it is working great! Of course, except a small adjustment required for nVidia card and a possible toggling maneuver for one BIOS setting [Memory Map IO above 4GB] if OC failed to boot.

Again, thank you for sharing your work and your assistance!
 
BTW - I could not catch the screen panic message via OC boot log, since the message was originated from macOS, after OC finished its booting role.
